using hospital.Models.Report.ReportDto;
using hospital.Repository.Interface;
using hospital.Services.Interface;

namespace hospital.Services
{
    // Service layer responsible for generating and retrieving reports
    public class ReportService : IReportService
    {
        // Repository dependency for report-related database operations
        private readonly IReportRepository _reportRepository;

        // Constructor Dependency Injection
        public ReportService(IReportRepository reportRepository)
        {
            _reportRepository = reportRepository;
        }

        // Retrieves a detailed appointment report
        public async Task<List<AppointmentReportDto>> GetAppointmentReportAsync()
        {
            // Call repository method to fetch appointment report data
            return await _reportRepository.GetAppointmentReportAsync();
        }

        // Retrieves appointment count grouped by doctor
        public async Task<List<DoctorAppointmentCountDto>> GetDoctorAppointmentCountAsync()
        {
            // Call repository method to fetch doctor-wise appointment counts
            return await _reportRepository.GetDoctorAppointmentCountAsync();
        }

        // Retrieves revenue generated by each doctor specialization
        public async Task<List<RevenueBySpecializationDto>> GetRevenueBySpecializationAsync()
        {
            // Call repository method to fetch specialization-wise revenue report
            return await _reportRepository.GetRevenueBySpecializationAsync();
        }

        // Retrieves all appointments scheduled within the next 7 days
        public async Task<List<UpcomingAppointmentDto>> GetUpcomingAppointmentsNext7DaysAsync()
        {
            // Call repository method to fetch upcoming appointments
            return await _reportRepository.GetUpcomingAppointmentsNext7DaysAsync();
        }
    }
}